# Generated by Django 2.1.7 on 2019-03-31 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Senza titolo', max_length=300)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('media', models.CharField(blank=True, choices=[('painting', 'Dipinto'), ('photography', 'Fotografia')], max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artworks')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='art.Artist')),
            ],
        ),
    ]
